generate report continue even though the test fail 3

diff --git a/.github/workflows/pipeline.yml b/.github/workflows/pipeline.yml
--- a/.github/workflows/pipeline.yml
+++ b/.github/workflows/pipeline.yml
@@ -29,20 +29,20 @@ jobs:
       run: npm install
     - name: "run unit test and generate reports"
       run: |
-            mkdir -p test-reports
-            if npm test -- --json --outputFile=test-reports/test-report.json; then
-              echo "Tests passed"
-            else
-              echo "Tests failed, generating report..."
-            # Upload the report even if tests fail
-            exit 1
-            fi
-      continue-on-error: true 
+           mkdir -p test-reports
+           npm test -- --json --outputFile=test-reports/test-report.json || echo "Tests failed, generating report..."
+      shell: bash
+
     - name: "upload test-report as artifact"
-      uses:  actions/upload-artifact@v4
+      uses: actions/upload-artifact@v4
       with:
         name: test-report
         path: test-reports/test-report.json
+        
+    # Fail the job if the tests failed
+    - name: "Fail job if tests failed"
+      if: ${{ failure() }}
+      run: exit 1
     
     
   build_and_push:
