generate report continue even though the test fail 6

diff --git a/.github/workflows/pipeline.yml b/.github/workflows/pipeline.yml
--- a/.github/workflows/pipeline.yml
+++ b/.github/workflows/pipeline.yml
@@ -29,26 +29,29 @@ jobs:
       run: npm install
     - name: "run unit test and generate reports"
       run: |
-          mkdir -p test-reports
-          npm test -- --json --outputFile=test-reports/test-report.json || TEST_FAILED=$?
-          if [ -n "${TEST_FAILED}" ]; then
-            echo "Tests failed, generating report..."
-          exit 1
-          fi
+           mkdir -p test-reports
+           npm test -- --json --outputFile=test-reports/test-report.json || TEST_FAILED=$?
+           # Check if the tests failed
+           if [ -n "${TEST_FAILED}" ]; then
+            echo "Tests failed, but report will still be generated."
+           fi
       shell: bash
-      continue-on-error: true
     - name: "upload test-report as artifact"
       uses: actions/upload-artifact@v4
       with:
         name: test-report
         path: test-reports/test-report.json
-      continue-on-error: false
+    - name: "Fail job if tests failed"
+      if: ${{ failure() }}
+      run: exit 1
     
     
   build_and_push:
 
     runs-on: ubuntu-latest
     needs: ["code_analysis_job", "unit_testing_job"]
+    if: needs.unit_testing_job.result == 'success'
+
     steps:
     - name: "checkout repository"
       uses: actions/checkout@v4
